---
- hosts: test
  collections:
  - ibm.ibm_zos_core
  gather_facts: false
  environment: '{{ environment_vars }}'
  tasks:
    - name: trigger_broadcom_scrt_esp_event
      zos_operator: 
        cmd: 'F ESPT,TRIGGER SYMVSPP.CA_SCRT ADD'
      register: result1
