# IBM Open Enterprise SDK Python and Z Open Automation Utilities (ZOAU) paths
PYZ: "/usr/lpp/IBM/cyp/v3r8/pyz"
ZOAU: "/products/zoautil"
# Python Interpreter
ansible_python_interpreter: "{{ PYZ }}/bin/python3.8"
